name: Build Manylinux Wheel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install twine
          pip install cython
          pip install auditwheel

      - name: Build Cython files
        run: |
          python setup.py build_ext --inplace

      - name: Build wheel
        run: |
          python setup.py bdist_wheel

      - name: Repair manylinux wheel
        run: |
          auditwheel repair dist/*.whl

      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: wheelhouse/
